pulseaudio: YP requires Upstream-Status in patches
YP requires Upstream-Status in patches else it will error out as
shown below.

ERROR: pulseaudio-16.1-r0 do_patch: QA Issue: Missing Upstream-Status in patch

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>