arduino-toolchain_1.0.bb: Update arduino-toolchain and related debian package binary versions
AVR depends on mpfr. The current recipe requires libmpfr.so.4 as seen in
the error below:
ERROR:arduino-toolchain-1.0-r0 do_package_qa: QA Issue:
/usr/lib/gcc/avr/4.9.2/lto1 contained in package arduino-toolchain
requires libmpfr.so.4()(64bit), but no providers found in
RDEPENDS_arduino-toolchain? [file-rdeps]
ERROR: arduino-toolchain-1.0-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: arduino-toolchain-1.0-r0 do_package_qa: Function failed:

Since mpfr version is updated in thud, it generates libmpfr.so.6. To fix
this dependency issue we need to upgrade the current binaries being used
in this recipes to the latest versions.

Signed-off-by: Sai Hari Chandana Kalluri <chandana.kalluri@xilinx.com>
Signed-off-by: Jaewon Lee <jaewon.lee@xilinx.com>
Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>