nativesdk-packagegroup-protobuf-sdk-host: Set PACKAGE_ARCH to avoid error
 ERROR: nativesdk-packagegroup-protobuf-sdk-host-1.0-r0 do_package_write_rpm: An allarch packagegroup shouldn'\''t depend on packages which are dynamically renamed (nativesdk-protobuf-c to nativesdk-libprotobuf-c1)

The PACKAGE_ARCH needs to be set to NOT 'all' BEFORE packagegroup is
inherited.  The nativesdk inherit will then override it (later) and set it
to the final value.

Signed-off-by: Mark Hatle <mark.hatle@amd.com>