plnx-image.bbclass: Move to greengrass-bin
Specifying the demo is currently broken, this results in:

  Error: Transaction test error:
     file /greengrass/v2/config/config.yaml conflicts between attempted installs of greengrass-bin-demo-1.0-r0.0.cortexa72_cortexa53 and greengrass-bin-2.14.1-r0.0.cortexa72_cortexa53

Signed-off-by: Mark Hatle <mark.hatle@amd.com>