petalinux-image-full.bb: Remove cpio.bz2 from full image
Fix issue while building cpio images

4376108 blocks
cpio: cannot seek on output: Invalid argument
ERROR: Function failed: do_image_cpio

This happens due to the cpio valid size being exceeded. Remove from cpio
and its variants from full image build

Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>