petalinux-features.conf: Add xilinx to LICENSE_FLAGS_WHITELIST
mesa-demos PROVIDES virtual/libgles1 as well as libmali-xlnx PROVIDES
virtual/libgles1. When buildling petalinux-image-full the following
error occurs:

ERROR: Nothing PROVIDES 'virtual/libgles1' (but
../sources/core/meta/recipes-graphics/mesa/mesa-demos_8.3.0.bb
DEPENDS on or otherwise requires it) mesa PROVIDES virtual/libgles1 but
was skipped:
PREFERRED_PROVIDER_virtual/libgl set to mesa-gl, not mesa
libmali-xlnx PROVIDES virtual/libgles1 but was skipped: because it has a
restricted license not whitelisted in LICENSE_FLAGS_WHITELIST

To fix this, we add xilinx license to LICENSE_FLAGS_WHITELIST

Signed-off-by: Sai Hari Chandana Kalluri <chandana.kalluri@xilinx.com>
Signed-off-by: Jaewon Lee <jaewon.lee@xilinx.com>
Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>