petalinux-image-minimal: Remove vek280-pl-aie-vdu-fw
Remove vek280-pl-aie-vdu-fw package as vek280-pl-aie-vdu-fw recipe
no longer exists. Due to this parse errors are observed.

ERROR: Nothing RPROVIDES 'vek280-pl-aie-vdu-fw' (but /scratch/sandeep/yocto/2025.2/yp-edf/sources/poky/../meta-petalinux/recipes-core/images/petalinux-image-minimal.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'vek280-pl-aie-vdu-fw' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['vek280-pl-aie-vdu-fw']
ERROR: Required build target 'petalinux-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['petalinux-image-minimal', 'vek280-pl-aie-vdu-fw']

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>