packagegroup-petalinux-ros: Enable ros packagegroup for langdale
1. Fix ros dynamic packages errors.
2. Remove python-nose which is pyhton2 based.
3. Remove demo-nodes-py and examples-rclpy-minimal-action-client due
   to below conflict errors.

Error: Transaction test error:
  file /usr/bin/listener conflicts between attempted installs of \
  examples-rclpy-executors-0.15.0+2-r0.0.cortexa72_cortexa53 and \
  demo-nodes-py-0.20.1+2-r0.0.cortexa72_cortexa53

  file /usr/bin/talker conflicts between attempted installs of \
  examples-rclpy-executors-0.15.0+2-r0.0.cortexa72_cortexa53 and \
  demo-nodes-py-0.20.1+2-r0.0.cortexa72_cortexa53

  file /usr/bin/client conflicts between attempted installs of \
  examples-rclpy-minimal-client-0.15.0+2-r0.0.cortexa72_cortexa53 and \
  examples-rclpy-minimal-action-client-0.15.0+2-r0.0.cortexa72_cortexa53

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>