packagegroup-petalinux-qt-extended: Fix qt dynamic pkgs errors
Fix qt dynamic packages errors:

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtx11extras-dbg to libqt5x11extras-dbg)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtsensors-mkspecs to libqt5sensors-mkspecs)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtsensors-plugins to libqt5sensors-plugins)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtserialport-mkspecs to libqt5serialport-mkspecs)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtsvg-mkspecs to libqt5svg-mkspecs)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtsvg-plugins to libqt5svg-plugins)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtwebchannel-mkspecs to libqt5webchannel-mkspecs)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtwebsockets-mkspecs to libqt5websockets-mkspecs)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtx11extras to libqt5x11extras5)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtxmlpatterns-mkspecs to libqt5xmlpatterns-mkspecs)

ERROR: packagegroup-petalinux-qt-extended-1.0-r0 do_package_write_rpm:
An allarch packagegroup shouldn't depend on packages which are
dynamically renamed (qtx11extras-dev to libqt5x11extras-dev)

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>