kernel-fitimage.bbclass: Don't use unit addresses on FIT
Manually rebasing and backporting hardknott upstream commit:
cfc0e21b1066b5d5d0fc37fbc5d79f40f4576f1d

Will fix the following issues we are seeing at bootup:

Node name contains @ in 'kernel@1' image node
Bad Data Hash
ERROR: can't get kernel image!
Bad Linux ARM64 Image magic!

Here is the upstream commit message:

    Das U-Boot 2021.4-rc1 has the following commit:

        commit 3f04db891a353f4b127ed57279279f851c6b4917
        Author: Simon Glass <sjg@chromium.org>
        Date:   Mon Feb 15 17:08:12 2021 -0700

            image: Check for unit addresses in FITs

            Using unit addresses in a FIT is a security risk. Add a check for
            this and disallow it.

            CVE-2021-27138

    Adjust the kernel-fitimage.bbclass accordingly to not use unit
    addresses. This changte is required before we can bump U-Boot to 2021.4.

    (From OE-Core rev: 6047be9f8f0f5d616fda11d83b682c1b8aeaa0ae)

    Signed-off-by: Klaus Heinrich Kiwi <klaus@linux.vnet.ibm.com>
    Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

Signed-off-by: Jaewon Lee <jaewon.lee@xilinx.com>