petalinux-image-full.bb: removing system controller from full image
Removing system controller from full image due to esdk build failure
The esdk build failure is:

ERROR: Task python3-click-native.do_fetch attempted to execute
unexpectedly
...

This patch removes packagegroup as a workaround

Signed-off-by: Jaewon Lee <jaewon.lee@xilinx.com>
Signed-off-by: Manjukumar Matha <manjukumar.harthikote-matha@xilinx.com>