buildtools-tarball.bbappen: Update nativesdk-python to nativesdk-python3
Python2 support is deprecated in dunfell. Hence during bitbake parsing it errors out with the followign error:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'nativesdk-python' (but buildtools-tarball.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'nativesdk-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['nativesdk-python']
ERROR: Required build target 'petalinux-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['petalinux-image-minimal', 'buildtools-tarball', 'nativesdk-python']

Fix the error by replacing nativesdk-python with nativesdk-python3

Signed-off-by: Sai Hari Chandana Kalluri <chandana.kalluri@xilinx.com>